{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hiyuuu",
    "module": "mclibrary",
    "version": "1.3.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mclibrary-1.3.18.jar",
          "url": "mclibrary-1.3.18.jar",
          "size": 110505,
          "sha512": "6f8513f5352103d9b871855f5c19d734d00a2b0523b9a4560d00ac1e3f2bb03da4c0bdbe1b936cf9feb9fbae56bfaa244e80e0a57b48bec9529bea476f4b2b1a",
          "sha256": "355a53791e14db440708932321b1540d9870f1f5dfebd9e24fc8642529307681",
          "sha1": "eb9ad72b918b8cb203027ee73dbabb62157c440c",
          "md5": "949f830a684b0f5ed0d6551b55dd18e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "mclibrary-1.3.18.jar",
          "url": "mclibrary-1.3.18.jar",
          "size": 110505,
          "sha512": "6f8513f5352103d9b871855f5c19d734d00a2b0523b9a4560d00ac1e3f2bb03da4c0bdbe1b936cf9feb9fbae56bfaa244e80e0a57b48bec9529bea476f4b2b1a",
          "sha256": "355a53791e14db440708932321b1540d9870f1f5dfebd9e24fc8642529307681",
          "sha1": "eb9ad72b918b8cb203027ee73dbabb62157c440c",
          "md5": "949f830a684b0f5ed0d6551b55dd18e2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mclibrary-1.3.18-all.jar",
          "url": "mclibrary-1.3.18-all.jar",
          "size": 2499992,
          "sha512": "cda0807a903fee31e7923b2b091fab9c05afe8c7005011bcdbff8940d37fc2ae5ca004ff3e6ed22ac3fa31cfdc4901fd6cf955ee6891ce4253a1f7646128366d",
          "sha256": "4193d5cf463e1d97e8c5201feb28927cc318b00dd54a1d91d4f20a7c8cbfed46",
          "sha1": "3440dbf96d827be5f3a925de6b2e5348009da4c5",
          "md5": "69053a508e981312ee293cdfc79b0b15"
        }
      ]
    }
  ]
}
