name: プルリクエストを生成

on:
  push:
    branches: [ develop ]

permissions:
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PRを作成
        continue-on-error: true
        run: gh pr create -B "master" -t "ブランチマージ： develop → master" -b ""
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}